# Generated by Django 5.2.12 on 2026-03-25 04:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wordsapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="en",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="word",
            name="fr",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="word",
            name="gender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="words",
                to="wordsapp.gender",
            ),
        ),
        migrations.AlterField(
            model_name="word",
            name="ru",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
