# Generated by Django 2.2.1 on 2019-06-02 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wordsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='knowledge_level',
        ),
        migrations.AddField(
            model_name='word',
            name='definition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='example',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='export_to_anki',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='word',
            name='exported_to_anki',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='word',
            name='known',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='theme',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='wordsapp.Theme'),
        ),
    ]
