# Generated by Django 5.2.12 on 2026-03-25 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wordsapp", "0002_alter_word_en_alter_word_fr_alter_word_gender_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="word",
            name="gender",
        ),
        migrations.AddField(
            model_name="word",
            name="frequency",
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="word",
            name="gender_fr",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="words_fr",
                to="wordsapp.gender",
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="gender_ru",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="words_ru",
                to="wordsapp.gender",
            ),
        ),
        migrations.AddField(
            model_name="word",
            name="user_added",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="words",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="word",
            name="en",
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "word",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="wordsapp.word",
                    ),
                ),
            ],
        ),
    ]
