# Generated by Django 2.2.1 on 2019-06-03 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsapp', '0002_auto_20190602_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='gender_rule',
            field=models.BooleanField(default=False, db_column='gender_rule')
        ),
        migrations.RenameField(
            model_name='word',
            old_name='gender_rule',
            new_name='gender_exception'
        ),
    ]
