# Generated by Django 5.2.12 on 2026-03-25 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("wordsapp", "0003_remove_word_gender_word_frequency_word_gender_fr_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="word",
            name="gender_ru",
        ),
        migrations.RemoveField(
            model_name="word",
            name="gender_fr",
        ),
        migrations.DeleteModel(
            name="Gender",
        ),
    ]
