# Generated by Django 5.2.12 on 2026-03-25 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wordsapp", "0004_remove_word_gender_ru_remove_word_gender_fr_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[("en", "English"), ("fr", "French")],
                        max_length=2,
                    ),
                ),
                ("repetition", models.PositiveIntegerField(default=0)),
                ("interval_days", models.PositiveIntegerField(default=0)),
                ("easiness_factor", models.FloatField(default=2.5)),
                ("due_at", models.DateTimeField()),
                (
                    "last_reviewed_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("last_quality", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "last_grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("again", "Again"),
                            ("hard", "Hard"),
                            ("easy", "Easy"),
                        ],
                        max_length=16,
                    ),
                ),
                ("total_reviews", models.PositiveIntegerField(default=0)),
                ("successful_reviews", models.PositiveIntegerField(default=0)),
                (
                    "record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_progresses",
                        to="wordsapp.record",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_progresses",
                        to="wordsapp.user",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "record", "language"),
                        name="wordsapp_studyprogress_user_record_language_uniq",
                    )
                ],
            },
        ),
    ]
