# Generated by Django 5.2.12 on 2026-03-25 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wordsapp", "0005_studyprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="word",
            name="comment",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
