# Generated by Django 5.2.12 on 2026-03-25 21:30

from django.db import migrations, models


def migrate_study_grades_to_binary(apps, schema_editor):
    """Map legacy study grades onto the new binary grade set."""
    StudyProgress = apps.get_model("wordsapp", "StudyProgress")
    StudyProgress.objects.filter(last_grade="again").update(last_grade="incorrect")
    StudyProgress.objects.filter(last_grade__in=["hard", "easy"]).update(
        last_grade="correct"
    )


class Migration(migrations.Migration):

    dependencies = [
        ("wordsapp", "0006_word_comment"),
    ]

    operations = [
        migrations.RunPython(
            migrate_study_grades_to_binary,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="studyprogress",
            name="last_grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("incorrect", "Incorrect"),
                    ("correct", "Correct"),
                ],
                max_length=16,
            ),
        ),
    ]
