# Generated by Django 5.2.12 on 2026-03-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wordsapp", "0007_binary_study_grades"),
    ]

    operations = [
        migrations.AddField(
            model_name="studyprogress",
            name="ignore",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="studyprogress",
            name="last_grade",
            field=models.CharField(
                blank=True,
                choices=[
                    ("incorrect", "Incorrect"),
                    ("correct", "Correct"),
                    ("ignore", "Ignore"),
                ],
                max_length=16,
            ),
        ),
    ]
