# Generated by Django 5.2.12 on 2026-03-25 23:00

from django.db import migrations


def ignore_correct_study_progress(apps, schema_editor):
    """Mark previously correct study progress rows as ignored."""
    StudyProgress = apps.get_model("wordsapp", "StudyProgress")
    StudyProgress.objects.filter(last_grade="correct").update(ignore=True)


class Migration(migrations.Migration):

    dependencies = [
        ("wordsapp", "0008_studyprogress_ignore"),
    ]

    operations = [
        migrations.RunPython(
            ignore_correct_study_progress,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
