# Generated by Django 5.2.12 on 2026-04-06 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wordsapp", "0010_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="ru",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="word",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("en", ""), _negated=True),
                    models.Q(("fr", ""), _negated=True),
                    _connector="OR",
                ),
                name="wordsapp_word_en_or_fr_required",
            ),
        ),
    ]
