---
name: Reusable Test
on:
  workflow_call:
jobs:
  reusable_test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up Python
        uses: actions/setup-python@v5.6.0
        with:
          python-version: "3.13"

      - name: Set up Node.js
        uses: actions/setup-node@v4.4.0
        with:
          cache: yarn
          cache-dependency-path: frontend/yarn.lock
          node-version: 20

      - name: Install linters binaries
        run: make install-linters-binaries

      - name: Install shellcheck
        run: sudo apt install shellcheck -y

      - name: Install uv
        run: pip3 install uv

      - name: Install tox
        run: pip install tox

      - name: Install Python dependencies
        run: uv sync

      - name: Enable corepack
        run: corepack enable

      - name: Install frontend dependencies
        run: make yarn-install-locked

      - name: Run tests
        run: make test
